# Generated by Django 3.2.9 on 2021-11-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_eathabittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouthierarchy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scouthierarchy', to='authentication.scouthierarchy'),
        ),
    ]
