// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    GithubIcon: typeof import('./src/components/icons/GithubIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/inputs/Input.vue')['default']
    InstagramIcon: typeof import('./src/components/icons/InstagramIcon.vue')['default']
    PrimaryButton: typeof import('./src/components/buttons/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/buttons/SecondaryButton.vue')['default']
    TextInput: typeof import('./src/components/inputs/TextInput.vue')['default']
  }
}

export { }
