// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/icons/AppIcon.vue')['default']
    Avatar: typeof import('./src/components/Avatar/Avatar.vue')['default']
    AvatarIcon: typeof import('./src/components/dashboardOld/AvatarIcon.vue')['default']
    AvatarText: typeof import('./src/components/dashboardOld/AvatarText.vue')['default']
    ButtonFancy: typeof import('./src/components/dashboardOld/ButtonFancy.vue')['default']
    Divider: typeof import('./src/components/divider/Divider.vue')['default']
    DropdownInput: typeof import('./src/components/inputs/DropdownInput.vue')['default']
    FileInput: typeof import('./src/components/inputs/FileInput.vue')['default']
    FilterIcon: typeof import('./src/components/searchbar/FilterIcon.vue')['default']
    GroupCard: typeof import('./src/components/groupCard/GroupCard.vue')['default']
    Main: typeof import('./src/components/searchbar/Main.vue')['default']
    ModalWithSlot: typeof import('./src/components/modal/ModalWithSlot.vue')['default']
    NavigationElement: typeof import('./src/components/layout/sideBarNavigation/NavigationElement.vue')['default']
    Old_ConfirmationModal: typeof import('./src/components/modal/old_ConfirmationModal.vue')['default']
    PrimaryButton: typeof import('./src/components/button/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/button/SecondaryButton.vue')['default']
    SideBarNavigation: typeof import('./src/components/layout/sideBarNavigation/SideBarNavigation.vue')['default']
    Tag: typeof import('./src/components/tag/Tag.vue')['default']
    TertiaryButton: typeof import('./src/components/button/TertiaryButton.vue')['default']
    TextInput: typeof import('./src/components/inputs/TextInput.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    UserActions: typeof import('./src/components/dashboardOld/UserActions.vue')['default']
    UserDetails: typeof import('./src/components/dashboardOld/UserDetails.vue')['default']
    UserIdentifier: typeof import('./src/components/dashboardOld/UserIdentifier.vue')['default']
    UserIdentifierBig: typeof import('./src/components/dashboardOld/UserIdentifierBig.vue')['default']
    UserList: typeof import('./src/components/dashboardOld/UserList.vue')['default']
    UserListEntry: typeof import('./src/components/dashboardOld/UserListEntry.vue')['default']
    UserRolesFancy: typeof import('./src/components/dashboardOld/UserRolesFancy.vue')['default']
  }
}

export { }
